name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: gradle build

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.1
    
    - name: Bump Versions
      uses: remorses/bump-version@v8
