name: CI

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: gradle build

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
    - name: Deploy service to Cloud Run
      uses: stefda/action-cloud-run@1.0.0
      with:
        service_key: ${{ secrets.GCP_CLOUD_RUN_SERVICE_KEY }}
        project: cohesive-envoy-270108
        registry: eu.gcr.io
        region: europe-north1

